### PR TITLE
Fix addtrack matrix

### PR DESCRIPTION
**Pull request by F-howk**

### CODE REVIEW

**Comment by DenizUgur** [comment]
Already applied at master

**Comment by F-howk** [comment]
> Already applied at master

matirx fix is not available in master

**Comment by DenizUgur** [comment]
See here:
https://github.com/gpac/mp4box.js/blob/4b20c3bb5b106d3aaa6897de24f724785a742f2a/src/isofile-advanced-creation.js#L16

**Comment by DenizUgur** [comment]
Oh, wait, my mistake. I'll push that fix to the master. Thanks!

**Comment by F-howk** [comment]
> See here:
> 
> https://github.com/gpac/mp4box.js/blob/4b20c3bb5b106d3aaa6897de24f724785a742f2a/src/isofile-advanced-creation.js#L16

addTrack this function

**Comment by DenizUgur** [comment]
It's there now

**Comment by F-howk** [comment]
> It's there now

This is an invalid matrix

**Comment by DenizUgur** [comment]
How so? I've updated it with your matrix and cross-checked with gpac.

**Comment by F-howk** [comment]
> How so? I've updated it with your matrix and cross-checked with gpac.

👍

**Pull request closed without merging**
