### PR TITLE
load the URL given on the search parameters

### PR DESCRIPTION
**Pull request by DenizUgur**
Opened in place of #348

### CODE REVIEW

**Comment by DenizUgur** [comment]
@cconcolato Kindly bumping :)

**Comment by DenizUgur** [comment]
@cconcolato Kindly bumping this PR again 🙂

**Comment by cconcolato** [comment]
Can you explain what issue this is fixing?

**Comment by DenizUgur** [comment]
Loading a file from the query parameters is not working with the current state of the file reader demo. This is because there is no `load` function to call.

However, the correct function `httpload` with proper arguments completes the loading flow.

Example of an URL that doesn't work and with this fix it should be working again: https://gpac.github.io/mp4box.js/test/filereader.html?https://mpeggroup.github.io/FileFormatConformance/files/published/isobmff/21_segment.mp4

**Comment by cconcolato** [comment]
Oh, you mean, one has currently to hit the "Load" button and the change is removing the need for it?

**Comment by DenizUgur** [comment]
To be honest, I never thought about hitting Load because it felt like it didn't do anything at all. But yeah, this would load the file immediately.

**Review by cconcolato — APPROVED** [review]

**Pull request merged**
