### PR TITLE
udes: initial implementation of UserDescriptionProperty

### PR DESCRIPTION
**Pull request by bradh**
This is from ISO/IEC 23008-12:2022 Section 6.5.20.

### CODE REVIEW

**Comment by bradh** [comment]
For an example that uses this, see https://github.com/nokiatech/heif/raw/gh-pages/content/heifv2/lights_1440x960.heic

**Review by cconcolato — APPROVED** [review]
Thank you.

**Comment by bradh** [comment]
@cconcolato is anything more required for this? I see a few others that went in, and this one is approved, so just wondering if the merge got overlooked.

**Review by cconcolato — APPROVED** [review]

**Comment by cconcolato** [comment]
Thank you. Just forgot to merge.

**Pull request merged**
