### PR TITLE
Package upgrades

### PR DESCRIPTION
**Pull request by jeanphilipperuijs**
1. vscode devcontainer using node v22
2. package updates

### CODE REVIEW

**Comment by jeanphilipperuijs** [comment]
package updates and bonus devcontainer for use with vscode

**Comment by DenizUgur** [comment]
Hi, thank you for the PR. These are all development dependencies and I wouldn't want to risk breaking anything _yet_.

**Comment by jeanphilipperuijs** [comment]
Hi,
My pleasure. 
Not sure if it's really breaking, the tests seem fine with these package upgrades.
Maybe there are any additional checks worth adding?

**Comment by DenizUgur** [comment]
It's most likely okay to merge but in the long run we may want to preserve the current codebase as much as possible. If, _hopefully_, we ever do a rewrite then the dependencies and all would be upgraded as well.

**Pull request closed without merging**
